# Generated by Django 4.2.5 on 2023-09-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionrequest',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='conversionrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
